services:
  backend:
    build:
      dockerfile: ../core.Dockerfile
    container_name: stock-api
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 8080:80
    volumes:
      - .:/app

  # frontend: